export type View = 'issues' | 'logs' | 'todos';
export const viewLabels: Record<View, string> = {
  issues: '问题修复',
  logs: '线上日志',
  todos: '我的待办',
};

export const issues = [
  {
    id: 'BUG-0248',
    title: '订单详情页偶发加载失败',
    app: '商城管理后台',
    priority: 'high',
    status: '处理中',
    updated: '12 分钟前',
    tag: '前端',
  },
  {
    id: 'BUG-0247',
    title: '导出的报表金额精度丢失',
    app: '数据报表',
    priority: 'high',
    status: '待处理',
    updated: '38 分钟前',
    tag: '后端',
  },
  {
    id: 'BUG-0246',
    title: '切换租户后菜单权限未刷新',
    app: '权限中心',
    priority: 'medium',
    status: '待处理',
    updated: '1 小时前',
    tag: '前端',
  },
  {
    id: 'BUG-0245',
    title: '批量导入时部分记录重复',
    app: '客户管理',
    priority: 'medium',
    status: '处理中',
    updated: '2 小时前',
    tag: '后端',
  },
  {
    id: 'BUG-0244',
    title: '移动端筛选面板被底部遮挡',
    app: '商城管理后台',
    priority: 'low',
    status: '待验证',
    updated: '今天 09:15',
    tag: '样式',
  },
  {
    id: 'BUG-0243',
    title: '搜索框清空后列表没有重置',
    app: '客户管理',
    priority: 'low',
    status: '已解决',
    updated: '昨天',
    tag: '前端',
  },
  {
    id: 'BUG-0242',
    title: '日期区间少展示最后一天',
    app: '数据报表',
    priority: 'medium',
    status: '已解决',
    updated: '昨天',
    tag: '后端',
  },
  {
    id: 'BUG-0241',
    title: '上传图片后预览比例异常',
    app: '商城管理后台',
    priority: 'low',
    status: '已解决',
    updated: '09 月 19 日',
    tag: '样式',
  },
] as const;

export const logRows = [
  {
    time: '10:42:38.291',
    level: 'ERROR',
    service: 'order-service',
    message: 'Failed to fetch order detail: upstream request timeout',
    trace: 'a8f21c09d4e7',
  },
  {
    time: '10:42:37.804',
    level: 'INFO',
    service: 'api-gateway',
    message: 'GET /api/v1/orders/2048 → 200 · 128ms',
    trace: 'b3e902f81a6c',
  },
  {
    time: '10:42:36.512',
    level: 'WARN',
    service: 'order-service',
    message: 'Connection pool usage above threshold: 85 / 100',
    trace: 'a8f21c09d4e7',
  },
  {
    time: '10:42:35.093',
    level: 'INFO',
    service: 'user-service',
    message: 'User session validated · user_id=usr_1024',
    trace: 'e4a70c25f9b3',
  },
  {
    time: '10:42:34.782',
    level: 'INFO',
    service: 'api-gateway',
    message: 'POST /api/v1/auth/refresh → 200 · 42ms',
    trace: 'c2d913a58e0f',
  },
  {
    time: '10:42:33.168',
    level: 'ERROR',
    service: 'order-service',
    message: 'Query execution exceeded 3000ms · operation=findById',
    trace: 'a8f21c09d4e7',
  },
  {
    time: '10:42:32.605',
    level: 'INFO',
    service: 'notification',
    message: 'Message delivered · channel=email · duration=86ms',
    trace: 'f1b62d94a0c8',
  },
  {
    time: '10:42:31.410',
    level: 'INFO',
    service: 'api-gateway',
    message: 'GET /api/v1/products?page=1 → 200 · 64ms',
    trace: 'd9c42a71e8f0',
  },
  {
    time: '10:42:30.227',
    level: 'WARN',
    service: 'user-service',
    message: 'Slow query detected · duration=1240ms',
    trace: 'b7e81f03c4d2',
  },
  {
    time: '10:42:29.083',
    level: 'INFO',
    service: 'order-service',
    message: 'Order created · order_id=ord_2056 · status=pending',
    trace: 'e5a29d80b1f7',
  },
  {
    time: '10:42:28.916',
    level: 'INFO',
    service: 'api-gateway',
    message: 'Health check passed · upstreams=4/4',
    trace: 'c8f10a36d2e9',
  },
  {
    time: '10:42:27.502',
    level: 'INFO',
    service: 'notification',
    message: 'Queue processed · pending=0 · duration=12ms',
    trace: 'a2d75b98f0e4',
  },
] as const;

export const todos = [
  {
    title: '整理本周的工作计划',
    category: '工作',
    due: '09:30',
    done: true,
    note: '把想到的事情都写下来',
  },
  {
    title: '完成个人工作台的页面设计',
    category: '工作',
    due: '今天',
    done: false,
    note: '先确定一个喜欢的方向',
    important: true,
  },
  {
    title: '读完《设计心理学》第三章',
    category: '学习',
    due: '今天',
    done: false,
    note: '留半小时给自己',
  },
  {
    title: '傍晚出去跑 5 公里',
    category: '生活',
    due: '18:30',
    done: false,
    note: '换个环境，放松一下',
  },
  {
    title: '整理桌面和下载文件夹',
    category: '生活',
    due: '今天',
    done: true,
    note: '清爽一点，效率高一点',
  },
] as const;

export const laterTodos = [
  {
    title: '整理常用的开发工具和资料',
    category: '工作',
    due: '明天',
    done: false,
    note: '',
  },
  {
    title: '想一想国庆假期去哪走走',
    category: '生活',
    due: '本周',
    done: false,
    note: '',
  },
  {
    title: '给自己的小项目写一份 README',
    category: '学习',
    due: '本周',
    done: false,
    note: '',
  },
] as const;
