/** Real HTTP + PiHost lifecycle, fully isolated data and scripted model turns. */
import assert from 'node:assert/strict';
import express from 'express';
import { once } from 'node:events';
import { join } from 'node:path';
import { mkdir, readFile, realpath, rm } from 'node:fs/promises';
import { PiHost } from '../server/pi/host';
import { WorkbenchStore } from '../server/workbench/store';
import { createModuleAgentsRouter } from '../server/module-agents/router';
import { assembleModuleAgent } from '../server/module-agents/assemble';
import { defaultAgentsConfigRoot, loadAgentProfiles } from '../server/module-agents/profiles';
import { ProfileSnapshots, profileRevision } from '../server/module-agents/snapshots';
import { sandbox, memorySettings, scripted } from './subagent-check-fixtures';
import { agentStorageKey, normalizeProjectCwd } from '../src/workbench-app/agents/session-storage.mjs';

const env = await sandbox();
env.runtime.hasConfiguredAuth = () => true;
const saved = process.env.PI_CODING_AGENT_DIR; process.env.PI_CODING_AGENT_DIR = env.agentDir;
const savedWorkspaceRoot = process.env.PI_WEBX_AGENT_WORKSPACE_ROOT;
process.env.PI_WEBX_AGENT_WORKSPACE_ROOT = join(env.root, 'agent-workspaces');
const store = new WorkbenchStore(join(env.root, 'workbench.sqlite'));
const host = new PiHost({ definitions: { read: async () => ({ schemaVersion: 1, revision: 1, path: join(env.root, 'defs.json'), agents: [] }) }, modelRuntimeFactory: async () => env.runtime, settingsManagerFactory: memorySettings, sessionDir: join(env.root, 'sessions') });
const originalCreate = host.create.bind(host);
/**
 * 配置里的模型按本机运行时目录填写，可能是 fixture 目录没有的自定义 provider；
 * 这个门禁验的是 cwd 绑定，直连创建也要换成 fixture 模型，否则测试会随本机配置而红。
 */
const fixtureModel = { provider: env.model.provider, model: env.model.id };
host.create = async options => originalCreate({ ...options, cwd: options.moduleAgent?.scope.agentId === 'codes' ? options.cwd : options.cwd ?? env.cwd, ...fixtureModel });
const profiles = await loadAgentProfiles(defaultAgentsConfigRoot());
const loaded = profiles.get('logs'); assert.ok(loaded?.ok);
const original = structuredClone(loaded.profile);
const snapshots = new ProfileSnapshots(join(env.root, 'snapshots'));
let stored: any[] = [];
const app = express(); app.use(express.json());
app.use('/api/module-agents', createModuleAgentsRouter({ host, store, profiles, workspaceKey: 'default', snapshots, storedSessions: async () => stored }));
const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
const base = `http://127.0.0.1:${(server.address() as any).port}/api/module-agents`;
const post = async (body: object, id = 'logs') => { const response = await fetch(`${base}/${id}/sessions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); return { status: response.status, body: await response.json() as any }; };
const unhandled: unknown[] = []; const capture = (error: unknown) => unhandled.push(error); process.on('unhandledRejection', capture);
try {
  const capabilitiesResponse = await fetch(base);
  assert.equal(capabilitiesResponse.status, 200);
  const capabilities = await capabilitiesResponse.json() as { agents: Array<{ id: string; ok: boolean; enabled: boolean; tools?: string[] }> };
  assert.deepEqual(capabilities.agents.map(agent => agent.id), ['requirements', 'codes', 'logs', 'works']);
  const worksCapability = capabilities.agents.find(agent => agent.id === 'works');
  assert.equal(worksCapability?.ok, true);
  assert.equal(worksCapability?.enabled, true);
  assert.deepEqual(worksCapability?.tools, ['works.context', 'works.schedule']);
  const concurrent = await Promise.all(Array.from({ length: 8 }, () => post({ requestId: 'same-create' })));
  assert.ok(concurrent.every(result => result.status === 200));
  const id = concurrent[0]!.body.session.id;
  assert.equal(new Set(concurrent.map(result => result.body.session.id)).size, 1);
  assert.equal(host.list().length, 1, 'same request creates exactly one session');
  assert.equal((await post({ requestId: 'same-create', sessionId: id })).status, 409, 'requestId cannot change target');
  const hosted = host.get(id)!;
  hosted.streaming = true;
  assert.equal((await post({ requestId: 'restore-running', sessionId: id })).status, 200);
  hosted.streaming = false;
  scripted(hosted.session, turn => turn === 1
    ? { content: [{ type: 'toolCall', id: 'logs-call', name: 'logs_search', arguments: { limit: 1 } }], stopReason: 'toolUse' }
    : { content: [{ type: 'text', text: 'fixture completed' }], stopReason: 'stop' });
  await hosted.session.prompt('query');
  assert.ok(hosted.session.messages.some(message => message.role === 'toolResult' && message.toolName === 'logs_search'));
  stored = [{ id, path: hosted.sessionFile, cwd: env.cwd }];
  await host.kill(id);
  const changed = structuredClone(original); changed.promptText = 'NEW-PROFILE-SENTINEL'; changed.skills[0]!.files['SKILL.md'] = 'NEW-SKILL-SENTINEL';
  changed.config.dataSources.logs!.id = 'new-source'; changed.profileRevision = profileRevision(changed);
  profiles.set('logs', { ok: true, profile: changed });
  const resumed = await Promise.all([post({ requestId: 'resume-a', sessionId: id }), post({ requestId: 'resume-b', sessionId: id })]);
  assert.ok(resumed.every(result => result.status === 200), JSON.stringify(resumed));
  assert.equal(host.list().length, 1, 'different requestIds restoring same session coalesce');
  const restored = host.get(id)!;
  assert.equal(restored.moduleAgent?.profileRevision, original.profileRevision);
  assert.ok(!restored.session.systemPrompt.includes('NEW-PROFILE-SENTINEL'));
  const oldSkill = await restored.session.getToolDefinition('skills_read')!.execute('skill', { name: 'log-analysis' }, undefined, undefined, {} as never);
  assert.ok(JSON.stringify(oldSkill).includes('先收窄范围'));
  const oldLogs = await restored.session.getToolDefinition('logs_search')!.execute('logs', { limit: 1 }, undefined, undefined, {} as never);
  assert.ok(JSON.stringify(oldLogs).includes('workbench-logs'));
  const fresh = await post({ requestId: 'new-profile' }); assert.equal(fresh.status, 200);
  assert.equal(host.get(fresh.body.session.id)?.moduleAgent?.profileRevision, changed.profileRevision);
  assert.ok(host.get(fresh.body.session.id)?.session.systemPrompt.includes('NEW-PROFILE-SENTINEL'));
  await host.kill(id);
  await rm(join(env.root, 'snapshots', `${original.profileRevision}.json`));
  assert.equal((await post({ requestId: 'missing-snapshot', sessionId: id })).status, 409);
  const broken = structuredClone(changed); broken.config.tools.push('unknown.tool'); broken.profileRevision = profileRevision(broken);
  profiles.set('logs', { ok: true, profile: broken });
  assert.equal((await post({ requestId: 'broken-config' })).status, 503);
  await new Promise(resolve => setTimeout(resolve, 20));
  assert.deepEqual(unhandled, [], 'failed requests do not leak rejected finally promises');
  const codesA = join(env.root, 'project-a');
  const codesB = join(env.root, 'project-b');
  await mkdir(codesA); await mkdir(codesB);
  const canonicalA = await realpath(codesA);
  const loadedCodes = profiles.get('codes');
  assert.ok(loadedCodes?.ok);
  const boundCodes = structuredClone(loadedCodes.profile);
  boundCodes.config.workspace = canonicalA;
  boundCodes.effectiveWorkspace = canonicalA;
  boundCodes.profileRevision = profileRevision(boundCodes);
  profiles.set('codes', { ok: true, profile: boundCodes });
  const codeWithoutCwd = await post({ requestId: 'codes-no-cwd' }, 'codes');
  assert.equal(codeWithoutCwd.status, 200, JSON.stringify(codeWithoutCwd));
  assert.equal(host.get(codeWithoutCwd.body.session.id)?.cwd, canonicalA);
  assert.equal((await post({ requestId: 'codes-relative', cwd: 'project-a' }, 'codes')).status, 400);
  assert.equal((await post({ requestId: 'codes-missing', cwd: join(env.root, 'missing') }, 'codes')).status, 400);
  assert.equal((await post({ requestId: 'logs-with-cwd', cwd: codesA })).status, 400);
  assert.equal((await post({ requestId: 'codes-other-project', cwd: codesB }, 'codes')).status, 409);
  const codeA = await post({ requestId: 'codes-create-a', cwd: codesA }, 'codes');
  assert.equal(codeA.status, 200, JSON.stringify(codeA));
  const codeId = codeA.body.session.id;
  const codeHosted = host.get(codeId)!;
  assert.equal(codeHosted.cwd, canonicalA);
  for (const name of ['read', 'grep', 'find', 'ls', 'edit', 'write']) {
    assert.ok(codeHosted.session.getToolDefinition(name), `codes has ${name}`);
  }
  assert.equal(codeHosted.session.getToolDefinition('bash'), undefined, 'codes cannot run shell');
  const codeWrite = codeHosted.session.getToolDefinition('write')!;
  await codeWrite.execute('codes-write', { path: 'codes-fixture.txt', content: 'bound project marker' }, undefined, undefined, {} as never);
  assert.equal(await readFile(join(codesA, 'codes-fixture.txt'), 'utf8'), 'bound project marker', 'real SDK write resolves relative to bound project');
  const codeRead = codeHosted.session.getToolDefinition('read')!;
  const readResult = await codeRead.execute('codes-read', { path: 'codes-fixture.txt' }, undefined, undefined, {} as never);
  assert.ok(JSON.stringify(readResult).includes('bound project marker'), 'real SDK read uses bound project');
  assert.equal((await post({ requestId: 'codes-cross-live', sessionId: codeId, cwd: codesB }, 'codes')).status, 409);
  assert.equal((await post({ requestId: 'codes-reuse-target', cwd: codesA }, 'codes')).status, 200);
  assert.equal((await post({ requestId: 'codes-reuse-target', cwd: codesB }, 'codes')).status, 409, 'requestId cannot change project');
  scripted(codeHosted.session, () => ({ content: [{ type: 'text', text: 'code fixture completed' }], stopReason: 'stop' }));
  await codeHosted.session.prompt('inspect project');
  stored.push({ id: codeId, path: codeHosted.sessionFile, cwd: codesA });
  await host.kill(codeId);
  assert.equal((await post({ requestId: 'codes-cross-disk', sessionId: codeId, cwd: codesB }, 'codes')).status, 409);
  const codeResume = await post({ requestId: 'codes-restore-a', sessionId: codeId, cwd: codesA }, 'codes');
  assert.equal(codeResume.status, 200, JSON.stringify(codeResume));
  assert.equal(host.get(codeId)?.cwd, canonicalA);
  const codeAssembly = () => assembleModuleAgent({ store, workspaceKey: 'default', agentId: 'codes', profile: boundCodes });
  const directCode = await originalCreate({ moduleAgent: await codeAssembly(), ...fixtureModel });
  assert.equal(directCode.cwd, canonicalA, 'direct host creation uses the bound project');
  await host.kill(directCode.id);
  await host.kill(codeId);
  await assert.rejects(originalCreate({ moduleAgent: await codeAssembly(), sessionPath: codeHosted.sessionFile!, cwd: codesB, ...fixtureModel }), /项目目录.*(?:不一致|不匹配)/,
    'direct host restoration cannot switch a code session to another project');
  assert.equal(normalizeProjectCwd(`${codesA}/./`), codesA);
  assert.notEqual(agentStorageKey('codes', codesA), agentStorageKey('codes', codesB));
  assert.equal(agentStorageKey('logs'), 'ai-workbench.agent-session:default:logs');
  assert.equal((await post({ requestId: 'works-with-cwd', cwd: codesA }, 'works')).status, 400);
  const worksSession = await post({ requestId: 'works-create' }, 'works');
  assert.equal(worksSession.status, 200, JSON.stringify(worksSession));
  const worksHosted = host.get(worksSession.body.session.id)!;
  assert.equal(worksHosted.moduleAgent?.agentId, 'works');
  assert.ok(worksHosted.session.systemPrompt.includes('工作助理 Agent'));
  assert.ok(worksHosted.session.getToolDefinition('works_context'));
  assert.ok(worksHosted.session.getToolDefinition('works_schedule'));
  assert.equal(worksHosted.session.getToolDefinition('requirements_save_draft'), undefined);
  await host.kill(worksHosted.id);
  console.log('PASS 模块 HTTP：创建幂等、运行中恢复、并发恢复、SDK 工具回合与快照；代码 Agent 真实目录、工具白名单、按项目恢复隔离');
} finally {
  process.removeListener('unhandledRejection', capture); server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve()));
  await host.disposeAll(); store.close(); if (saved === undefined) delete process.env.PI_CODING_AGENT_DIR; else process.env.PI_CODING_AGENT_DIR = saved;
  if (savedWorkspaceRoot === undefined) delete process.env.PI_WEBX_AGENT_WORKSPACE_ROOT; else process.env.PI_WEBX_AGENT_WORKSPACE_ROOT = savedWorkspaceRoot;
  await env.close();
}
